### ISSUE TITLE
let powell0 take over?

### ISSUE THREAD

**Issue by shaunc** [cludden/json-api-ify#30]
It would seem that [@powell0](https://github.com/powell0) is forging ahead with this. If you don't have time -- perhaps it would be good to convince him to take over? ... Or @powell0 could publish his fork to npm....

**Comment by cludden** [comment]
@shaunc I'd be more than happy to add @powell0 and anyone else as contributor to this repository. As of now, I have not received any PR/issues or formal interest

**Comment by powell0** [comment]
@cludden Sorry to take so long to respond to this.  

While I've been enhancing this library for my own needs, last week I ran into a performance problem with the library that makes it unusable for my needs.  I have a few cases where I need to serialize a large number of resources.  When serializing around ~1500 resources (around 25 primary resources and the rest included resources) it takes the library around 5000 ms to generate the JSON-API payload.  That's a deal breaker for my project so I'm going to switch off of this library and instead use [GaiamTV/transformalizer](https://github.com/GaiamTV/transformalizer) which can handle the same load in 100 ms.

Since I won't be doing any more work on my fork, I'd be happy to submit my changes as a PR to this repository so that others can continue on.
